### ISSUE TITLE
Plugin dependency management

### ISSUE THREAD

**Issue by derekstavis** [bucaran/fishline#509]
It would be great to have plugin dependency management in a way plugins can depend one upon other. This could be implemented without much heuristics, using a `.requires` file that's basically a fish script that uses global functions, like `Plugin` and `Theme` to chain requirements installation.

Example plugin called foo:

> plugin-foo/foo.requires

```
plugin.require "title"
```

> plugin-foo/foo.fish

```
function decorated_title
    set caption $argv[1]
    title "~ $caption ~"
end
```

This way `omf install` can source `.requires` only when installing or updating the package. The `plugin.require` function can ignore already installed packages and install the ones that aren't.

Comments? Ideas?

**Comment by derekstavis** [comment]
Another great use-case for this is the `nvm` plugin I'm willing to write:

> plugin-nvm/nvm.requires
```
plugin.require "foreign-env"
```
> plugin-nvm/nvm.fish
```
function nvm
    fenv source ~/.nvm/nvm.sh\; nvm $argv
end
```

**Comment by bucaran** [comment]
We had something similar to this before using `imports` inside a conditional. The problem is that fish concept of scope is very limited, and to require another plugin is equivalent to autoload and source the source code of the plugin which will pollute the global namespace.

What you can do is check whether the plugins your plugin requires are already loaded, and if not, warn the user.

**Comment by bpinto** [comment]
The way home brew handles it is to install these dependencies in a place only visible to this tool.

We might be able to namespace the dependencies so that we have access to the functions. We wouldn't load the init files though.

Not sure if it's worth though, thoughts?

**Comment by bpinto** [comment]
In your example we could namespace every function with nvm. So we would call the function as nvm.fenv

**Comment by bucaran** [comment]
> We might be able to namespace the dependencies so that we have access to the functions. We wouldn't load the init files though.

We can always autoload any functions, but the user is then responsible to appropriately namespace their functions.

**Comment by derekstavis** [comment]
Yeah @bpinto, this way we can do more complex stuff, like depending upon specific tags/refs. Looks a good idea. But I don't know how can we "rename" dependencies functions.

**Comment by derekstavis** [comment]
I prefer forcing plugin developer to namespace their functions, like `omf` have done, as a code style for upstream-acceptable plugins.

**Comment by bucaran** [comment]
This should be handled during the initialization of the plugin. Basically check whether the plugin you need exists or not. What would be useful to have is a way for plugins to express their deps so that when you download one its deps download along with it. This feature can be easily implemented when we are done merging with Wahoo. 

Basically we keep the URL of the plugin in a file, but we can add as many URLs as we want to that file, those would be the dependencies.

**Comment by derekstavis** [comment]
> What would be useful to have is a way for plugins to express their deps so that when you download one its deps download along with it.

This is what I mean.

**Comment by bucaran** [comment]
@derekstavis Got it and you'll have it in a few days.

**Comment by derekstavis** [comment]
> Basically check whether the plugin you need exists or not during initialization.

Yeah, this isn't mandatory, developers who want implement it. But Oh My Fish should install all needed dependencies on package install. 

> Basically we have a registry of files with URLs for each plugin.

No URLs, plugin names perform better, there are already a way to fetch and check them.

**Comment by bucaran** [comment]
> Yeah, this isn't mandatory, developers who want implement it. But Oh My Fish should install all needed dependencies on package install.

True. If OMF installs packages along with its dependencies you should not need to do that. :+1: 

> No URLs, plugin names perform better, there are already a way to fetch and check them. Our registry can continue as it is.

The current OMF registry mechanism will change. See Wahoo's [FAQ](https://github.com/wa/wahoo/blob/master/FAQ.md).
