### ISSUE TITLE
What happend with all the old plugins?

### ISSUE THREAD

**Issue by jschneider** [bucaran/fishline#520]
I have been using oh-my-fish for some time. And I used to use those plugins:

Plugin 'git-flow'
Plugin 'extract'
Plugin 'msg'
Plugin 'mc'
Plugin 'jump'
Plugin 'gi'

Only "extract" could be found with "omf get". What happened to the others?

**Comment by bucaran** [comment]
We are migrating to a new foundation and in the process we still need to add those older plugins. Some may even get a deserved rewrite. Please bear with us while we get this done. In the meantime, please have a look at the new [README](https://github.com/fish-shell/oh-my-fish#about).

**Comment by bpinto** [comment]
@jschneider `gi` plugin also exist. We are working on porting all the other plugins.

**Comment by sheldon** [comment]
Is the package format different? Perhaps we can import all the old packages in the meantime, until they get rewrites?

**Comment by bpinto** [comment]
It wouldn't be hard, as most would work if we did the following:

Add them to the db folder and add a source folder/*.load to our plugin initializer.

I'be been debating with myself whether its good or not to do. What do other think?

**Comment by bobthecow** [comment]
I feel like this is an opportunity to clean things up, make sure they have readmes, etc. I'm okay porting them one at a time. 

If someone really needs one that hasn't been ported yet, it's a great opportunity for them to get involved :P

**Comment by bpinto** [comment]
@bobthecow :+1:

**Comment by jschneider** [comment]
Maybe next time do the migration work within a separate branch?
I have just made a "git update" in oh-my-fish and suddenly been caught by an in-between-stand.

**Comment by bpinto** [comment]
@jscheider
What are you still missing? Most if not all daily use plugins have already been converted.

**Comment by bpinto** [comment]
Err... Most... Not all :)
