### ISSUE TITLE
git status --porcelain not very performant

### ISSUE THREAD

**Issue by bucaran** [bucaran/fishline#521]
@brejoc

> In fact it takes ages to complete with very big repos. Perhaps inspiration could come from zsh's vcs_info which manages to enter the directory without notable delay.

>Steps to reproduce:

>Start fish with e.g. the batman theme.
Navigate to a very big git repo.
Wait 20 seconds for fish to accept user input again.

See bucaran/wahoo/issues/77

**Comment by bobthecow** [comment]
@brejoc Give it a shot with bobthefish and see if that's any more performant?
