### ISSUE TITLE
`omf install URL` should strip package/theme from its name

### ISSUE THREAD

**Issue by bpinto** [bucaran/fishline#561]
`$ omf install https://github.com/oh-my-fish/plugin-rbenv`
Will clone the repo and add it a folder named `plugin-rbenv` but the folder should be named `rbenv` as `omf` will launch an event named `init_plugin-rbenv` which is unexpected.

**Comment by bobthecow** [comment]
;+1:

Related: for packages and themes with hyphens in their URL, should the event name be converted to underscore?

**Comment by bpinto** [comment]
I think this would be unexpected, why do you think we should convert it?

**Comment by bobthecow** [comment]
just because it's ugly :P 

it's fine, leave it as-is.

**Comment by bpinto** [comment]
:D
