### ISSUE TITLE
update directory structure

### ISSUE THREAD

**Issue by bucaran** [bucaran/fishline#580]
Change `lib` → `functions`
Change `pkg` → `plugin`
Change `plugins` → `plugin`
Change `themes` → `theme`

**Comment by bpinto** [comment]
> Change `lib` → `functions`

:+1: 

> Change `pkg` → `plugin`
> Change `plugins` → `plugin`
> Change `themes` → `theme`

I like renaming `pkg` to `plugin(s)`. But I'm not sure about making the folder name singular:

```
Applications   Documents      Library        Pictures       Downloads      Movies
         Desktop       VirtualBox VMs
```

**Comment by bucaran** [comment]
The idea of plural and singular is useless, but that is a different issue in linguistics. The benefit is simpler and smaller code. Because you don't have to remember if a s is needed or not.

**Comment by derekstavis** [comment]
This is much needed. But I agree with @bpinto on plurals:

Change `lib` → `functions`
Change `pkg` → `plugin`

This should be sufficient and could be done in two separated commits.

**Comment by bpinto** [comment]
> The benefit is simpler and smaller code.

That's enough. :+1:

**Comment by bucaran** [comment]
@derekstavis It's hard to explain without showing you any code, but in my Derek PR I was able to reduce code in some areas by using only the singular.
