### ISSUE TITLE
rewrite install script in fish

### ISSUE THREAD

**Issue by bucaran** [bucaran/fishline#581]
When I first wrote the install script I wrote it in `bash` because I wanted to install `fish` and even `git` if it was not found in the user's system. This worked, but the file was around 300~400 LOC and it was difficult to maintain.

Using `fish` would help reduce code size and prevent non fish users to install OMF.

**Comment by bpinto** [comment]
Prior to merge, OMF install script was written in fish. It was much simpler indeed. But I'm okay with both solutions.

**Comment by bucaran** [comment]
Indeed, it was.
