### ISSUE TITLE
Backwards compatibility layer (migrations)

### ISSUE THREAD

**Issue by derekstavis** [bucaran/fishline#584]
We need to implement a backward compatibility mechanism to allow us upgrade user installations transparently. I propose us to use a migration concept.

## Why migrations

Using migrations we can keep moving with core development while easing the upgrade impacts on user-side.

## What a migration looks like

Migrations are simple fish scripts which perform a __single__ task. A sample migration script:

> 201509011311-move-fish-config-to-bundle.fish

```fish
function migrate
  set -l OLD_OMF_CONFIG ~/.config/fish/config.fish
  set -l OLD_PLUGINS (grep "Plugin" $OLD_OMF_CONFIG 2> /dev/null)
  set -l OLD_THEMES (grep "Theme" $OLD_OMF_CONFIG 2> /dev/null)
  set -l BUNDLE_PATH $OMF_CONFIG/bundle

  for theme in $OLD_THEMES
    echo $theme | sed -e 's/Theme/theme/g;s/["|\']//g >> $BUNDLE_PATH
  end

  for plugin in $OLD_PLUGINS
    echo $theme | sed -e 's/Plugin/plugin/g;s/["|\']//g >> $BUNDLE_PATH
  end
end
```

## How migrations are executed

Migrations file names start with a date so they can be executed sequentially. We need to come with a way to migrate from/up to a specific commit. This could be done by using the `revision` file, which is kinda unused at this moment.

## How do we know a migration already run

The first thing I thought is that migrations already executed could write a receipt file into `$OMF_CONFIG/migrations`, but I find this too bulky.

**Comment by bpinto** [comment]
### Migration execution:

Migrations needs to be able to check whether they need to be executed or not. We can't rely on any other information.

### Migration skip

We can save the last executed migration on a `/migration` file to prevent checking/running a migration.

**Comment by derekstavis** [comment]
Great additions @bpinto :+1:
