### ISSUE TITLE
Installation script overwrites existing fish config file

### ISSUE THREAD

**Issue by nevyn** [bucaran/fishline#586]
Is there a reason why you are overwriting .config/fish/config.fish? Is append a viable alternative? I just installed omf on two computers and it overwrote essential configs on both of them :/

I see in the install script that it took a backup of my config first, but it'd be even nicer if it just appended to the end instead of overwriting.

**Comment by bpinto** [comment]
We've had this conversation before, the problem with appending is that we can not guarantee it's going to work, so we are going to have issues reporting errors that shouldn't happen.
Another reason is that we don't advise users to add configuration to the config.fish file, but instead to add them to custom plugins or to another file.

**Comment by bpinto** [comment]
I hope that makes sense :)

**Comment by bucaran** [comment]
@bpinto @bobthecow We need to draft a Q/A for this issue which comes up all the time.

Any one wants to give it a shot and add it to the FAQ? @derekstavis @nevyn ?

**Comment by bobthecow** [comment]
We could also make it a bit more verbose when it happens. "We found an existing config.fish file. We backed it up and added a new one. You'll need to copy anything you need over into `$OMF_CONFIG/init.fish` if you want it to keep working.

**Comment by derekstavis** [comment]
I like @bobthecow approach. Better than making assumptions about the config file :)

**Comment by bucaran** [comment]
Yes, why not. But this needs to go in the FAQ.

**Comment by derekstavis** [comment]
Yes @bucaran, this is also a must! :+1:

**Comment by sheldon** [comment]
Would it be possible to offer to copy the config for them? or even possibly do this by default to keep things working for most users?

I guess the answer lies in whether most people can just copy/paste or have to modify existing setup for some reason.

**Comment by bpinto** [comment]
It's not worth in my opinion, and you only need to do this once. It's hard for us to know what a user has in their config file.
